### ISSUE TITLE
Restructuring, Documenting and Organizing

### ISSUE THREAD

**Issue by ratnanil** [arc2r/book#107]
Hey Nikos,

I worked hard on this book all the way, but feel like I haven't been able to bring some order into our repo. I have the following tasks, which I really need your help with

## 1. Documenting our progress

It's unclear which ArcGIS Tools we already have covered and which are still open. There are several issues open to try and keep track (#58, #59, #60, #61, #62, #83) but I don't think you keep these up to date? I have the following suggestion: let's stop tracking the progress in issues, but in this yaml file: [auxiliary/tools_todo.yaml](https://github.com/arc2r/book/blob/master/auxiliary/tools_todo.yaml). The idea is that we replace the `NA` with an approximate progress (0 - 100). Can you help me on this? It would greatly help communicate the state of the project to Patrick, Daniela and everyone who's interested.

## 2. Location of the tools

Many tools seem to be located in the wrong place (not in the correct toolset or in the correct toolbox) Can you help me harmonize this as well? Check the [mentioned YAML file](https://github.com/arc2r/book/blob/master/auxiliary/tools_todo.yaml) to see the "correct" (ArcGIS) Structure of Toolbox / Toolset / Tools (For example, 

## 3. Data Structure 

The structure is not harmonized: I think the ideal structure would be the following, where either *each tool is documented in its own .Rmd-File* or *each toolset has it's own Rmd File*. We are currently closer to the second option, the first option would look like this:

```
1                           
2   °--Geoprocessing        
3       ¦--Toolbox          
4       ¦   °--ToolsetA     
5       ¦       ¦--Tool1.Rmd
6       ¦       °--Tool2.Rmd
7       °--Toolbox2         
8           ¦--ToolsetB     
9           ¦   ¦--Tool3.Rmd
10          ¦   °--Tool4.Rmd
11          °--ToolsetC     
12              ¦--Tool1.Rmd
13              °--Tool2.Rmd
```

Currently, all Tools are either placed in the .Rmd of the toolset and sometimes even in the toolbox. So that is the first thing we should harmonize. Can you help me on this?

**Comment by KimboGilda** [comment]
@ratnanil in the latest commit of mine, I am proposing the following document's structure, which is based on the data structure you've written above

**Restructuring -- Current state bako_branch**

- Changes

1. Data Management toolbox --> Layers and Table Views toolset
**Layers and Table Views.Rmd** instead of having indidual Rmds for the tools.

Layers and Table Views toolset
 -> Select by Attribute
 -> Select by Location

_Selection.Rmd file, we have to add maybe in the beginning of the file (after ## Layers and Table Views toolset)?_


Proposed _bookdown.yml

rmd_files: [
  "index.Rmd",
  
  "00_Data/Data.Rmd",
  "00_Data/import_vector.Rmd",
  "00_Data/import_raster_raster.Rmd",
  "00_Data/import_raster_terra.Rmd",
  
  "01_Making_Maps/Making_Maps.Rmd",
  "01_Making_Maps/Static_Maps.Rmd",
  "01_Making_Maps/Dynamic_Maps.Rmd",
  
  **Toolbox == Data Management** -- > Every .Rmd represents the respective _toolset_ --> within every toolset the respective _tool_
  "02_Data_Management/Data_Management.Rmd",
  "02_Data_Management/General.Rmd",
  "02_Data_Management/Layers_and_Table_Views.Rmd",
  "02_Data_Management/Join.Rmd",
  "02_Data_Management/Projections_and_Transformations.Rmd",
  "02_Data_Management/Raster_Processing.Rmd",
  "02_Data_Management/Sampling.Rmd",
  
  **Toolbox == Analysis**
  "03_Analysis/Analysis.Rmd",
  "03_Analysis/Extract_toolset.Rmd",
  "03_Analysis/Overlay_toolset.Rmd",
  "03_Analysis/Proximity_toolset.Rmd",
  
   **Toolbox == Image_Analyst**
  "04_Image_Analyst/Image_Analyst.Rmd",
  
  **Toolbox == 3D_Analyst**
  "05_3D_Analyst/3D_Analyst.Rmd",
  
  **Toolbox == Spatial_Analyst**
  "06_Spatial_Analyst/Spatial_Analyst.Rmd",
  
  "07_Topology_Rules.Rmd",
  "07_Topology_Rules/Polygon.Rmd",
  "07_Topology_Rules/Line.Rmd",
  "07_Topology_Rules/Point.Rmd",
  "07_Topology_Rules/Line_or_Polygon.Rmd",
  
  "bibliography.Rmd"
]
